baseURL = 'https://vincent-s-blog.web.app/'
languageCode = 'en-us, zh-TW, zh'
title = 'My New Hugo Site'
<<<<<<< HEAD
theme = 'ga-hugo-theme'
=======
>>>>>>> 697bd6b (first-commit)
tags = []
paginate = 8
staticDir = "static"
enableInlineShortcodes =  true

[permalinks]
  home = "/index.html"


[params]
  [params.mathjax]
    enable = true
    cdn = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-AMS-MML_HTMLorMML"


[markup]
[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true

