baseURL = 'https://vincent-s-blog.web.app/'
languageCode = 'en-us, zh-TW, zh'
title = 'My New Hugo Site'
theme = 'ga-hugo-theme'
tags = []
paginate = 8
staticDir = "static"


[permalinks]
  home = "/index.html"